name: Deploy to Droplet

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up the SSH key and known_hosts
      - name: Set up SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DROPLET_SSH_KEY }}
          known_hosts: |
            159.65.189.139

      # Step 3: Deploy the code and restart the bot
      - name: Deploy
        run: |
          ssh -v root@159.65.189.139 "cd /opt/kasutamaiza-bot && git pull && systemctl restart kasutamaiza-bot"