name: Deploy to Droplet

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DROPLET_SSH_KEY }}
          known_hosts: |
            159.65.189.139

      - name: Deploy
        run: |
          ssh root@159.65.189.139 "cd /opt/kasutamaiza-bot && git pull && systemctl restart kasutamaiza-bot"
